server:
  port: 8080
spring:
  application:
    name: "Loan-Service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
logging:
  level:
    com.creditya.authservice: trace
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "loan_db"
    schema: "public"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
